name: PR Build Check

concurrency: 
  group: "build pull request"
  cancel-in-progress: true

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: "src"

      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Initialize Secrets
        env:
          SUPERSTREAM_FIRST_API: ${{ secrets.SUPERSTREAM_FIRST_API }}
          SUPERSTREAM_SECOND_API: ${{ secrets.SUPERSTREAM_SECOND_API }}
          SUPERSTREAM_THIRD_API: ${{ secrets.SUPERSTREAM_THIRD_API }}
          SUPERSTREAM_FOURTH_API: ${{ secrets.SUPERSTREAM_FOURTH_API }}
          SUPERSTREAM_FIFTH_API: ${{ secrets.SUPERSTREAM_FIFTH_API }}
          TMDB_API: ${{ secrets.TMDB_API }}
          DUMP_API: ${{ secrets.DUMP_API }}
          DUMP_KEY: ${{ secrets.DUMP_KEY }}
          CRUNCHYROLL_BASIC_TOKEN: ${{ secrets.CRUNCHYROLL_BASIC_TOKEN }}
          CRUNCHYROLL_REFRESH_TOKEN: ${{ secrets.CRUNCHYROLL_REFRESH_TOKEN }}
          ZSHOW_API: ${{ secrets.ZSHOW_API }}
          SFMOVIES_API: ${{ secrets.SFMOVIES_API }}
          CINEMATV_API: ${{ secrets.CINEMATV_API }}
          GHOSTX_API: ${{ secrets.GHOSTX_API }}
          MOVIE_API: ${{ secrets.MOVIE_API }}
          MultiMovies_API: ${{ secrets.MultiMovies_API }}
          MovieDrive_API: ${{ secrets.MovieDrive_API }}
          AsianDrama_API: ${{ secrets.AsianDrama_API }}
          Whvx_API: ${{ secrets.Whvx_API }}
          WhvxAPI: ${{ secrets.WhvxAPI }}
          SharmaflixApi: ${{ secrets.SharmaflixApi }}
          SharmaflixApikey: ${{ secrets.SharmaflixApikey }}
          WASMAPI: ${{ secrets.WASMAPI }}
          WhvxT: ${{ secrets.WhvxT }}
          Vidsrccc: ${{ secrets.Vidsrccc }}
          StreamPlayAPI: ${{ secrets.StreamPlayAPI }}
          PROXYAPI: ${{ secrets.PROXYAPI }}
          KissKh: ${{ secrets.KissKh }}
          KisskhSub: ${{ secrets.KisskhSub }}
          GojoAPI: ${{ secrets.GojoAPI }}
          ANICHI_API: ${{ secrets.ANICHI_API }}
          CatflixAPI: ${{ secrets.CatflixAPI }}
        run: |
          cd $GITHUB_WORKSPACE/src
          echo SUPERSTREAM_FIRST_API=$SUPERSTREAM_FIRST_API >> local.properties
          echo SUPERSTREAM_SECOND_API=$SUPERSTREAM_SECOND_API >> local.properties
          echo SUPERSTREAM_THIRD_API=$SUPERSTREAM_THIRD_API >> local.properties
          echo SUPERSTREAM_FOURTH_API=$SUPERSTREAM_FOURTH_API >> local.properties
          echo SUPERSTREAM_FIFTH_API=$SUPERSTREAM_FIFTH_API >> local.properties
          echo TMDB_API=$TMDB_API >> local.properties
          echo DUMP_API=$DUMP_API >> local.properties
          echo DUMP_KEY=$DUMP_KEY >> local.properties
          echo CRUNCHYROLL_BASIC_TOKEN=$CRUNCHYROLL_BASIC_TOKEN >> local.properties
          echo CRUNCHYROLL_REFRESH_TOKEN=$CRUNCHYROLL_REFRESH_TOKEN >> local.properties
          echo ZSHOW_API=$ZSHOW_API >> local.properties
          echo SFMOVIES_API=$SFMOVIES_API >> local.properties
          echo CINEMATV_API=$CINEMATV_API >> local.properties
          echo GHOSTX_API=$GHOSTX_API >> local.properties
          echo MOVIE_API=$MOVIE_API >> local.properties
          echo MultiMovies_API=$MultiMovies_API >> local.properties
          echo MovieDrive_API=$MovieDrive_API >> local.properties
          echo AsianDrama_API=$AsianDrama_API >> local.properties
          echo Whvx_API=$Whvx_API >> local.properties
          echo WhvxAPI=$WhvxAPI >> local.properties
          echo SharmaflixApi=$SharmaflixApi >> local.properties
          echo SharmaflixApikey=$SharmaflixApikey >> local.properties
          echo WASMAPI=$WASMAPI >> local.properties
          echo WhvxT=$WhvxT >> local.properties
          echo Vidsrccc=$Vidsrccc >> local.properties
          echo StreamPlayAPI=$StreamPlayAPI >> local.properties
          echo PROXYAPI=$PROXYAPI >> local.properties
          echo KissKh=$KissKh >> local.properties
          echo KisskhSub=$KisskhSub >> local.properties
          echo GojoAPI=$GojoAPI >> local.properties
          echo ANICHI_API=$ANICHI_API >> local.properties
          echo CatflixAPI=$CatflixAPI >> local.properties

      # Change `**/**/build/*.flx` if you've changed the providers file structure.
      - name: Build providers
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make generateUpdaterJson